### ISSUE TITLE
Проблема запуска

### ISSUE THREAD

**Issue by dronchik** [BoberCoder/MongoDB_CLI#1]
Запустил приложение и получил ошибку:
```
MongoDB_CLI $ php mongocli.php
Welcome to MongoDB CLI. Available databases:
PHP Notice:  Undefined property: stdClass::$username in /Users/andrew/projects/MongoDB_CLI/mongocli.php on line 21

Notice: Undefined property: stdClass::$username in /Users/andrew/projects/MongoDB_CLI/mongocli.php on line 21
PHP Notice:  Undefined property: stdClass::$password in /Users/andrew/projects/MongoDB_CLI/mongocli.php on line 21

Notice: Undefined property: stdClass::$password in /Users/andrew/projects/MongoDB_CLI/mongocli.php on line 21
admin
local
Please enter database which you want to use: local

Enter your username:
And password:

Available collections in this database:
PHP Fatal error:  Uncaught MongoDB\Driver\Exception\AuthenticationException: Authentication failed. in /Users/andrew/projects/MongoDB_CLI/vendor/mongodb/mongodb/src/Operation/ListCollections.php:107
Stack trace:
#0 /Users/andrew/projects/MongoDB_CLI/vendor/mongodb/mongodb/src/Operation/ListCollections.php(107): MongoDB\Driver\Server->executeCommand('local', Object(MongoDB\Driver\Command))
#1 /Users/andrew/projects/MongoDB_CLI/vendor/mongodb/mongodb/src/Operation/ListCollections.php(83): MongoDB\Operation\ListCollections->executeCommand(Object(MongoDB\Driver\Server))
#2 /Users/andrew/projects/MongoDB_CLI/vendor/mongodb/mongodb/src/Database.php(298): MongoDB\Operation\ListCollections->execute(Object(MongoDB\Driver\Server))
#3 /Users/andrew/projects/MongoDB_CLI/mongocli.php(50): MongoDB\Database->listCollections()
#4 {main}
  thrown in /Users/andrew/projects/MongoDB_CLI/vendor/mongodb/mongodb/src/Operation/ListCollections.php on line 107

Fatal error: Uncaught MongoDB\Driver\Exception\AuthenticationException: Authentication failed. in /Users/andrew/projects/MongoDB_CLI/vendor/mongodb/mongodb/src/Operation/ListCollections.php:107
Stack trace:
#0 /Users/andrew/projects/MongoDB_CLI/vendor/mongodb/mongodb/src/Operation/ListCollections.php(107): MongoDB\Driver\Server->executeCommand('local', Object(MongoDB\Driver\Command))
#1 /Users/andrew/projects/MongoDB_CLI/vendor/mongodb/mongodb/src/Operation/ListCollections.php(83): MongoDB\Operation\ListCollections->executeCommand(Object(MongoDB\Driver\Server))
#2 /Users/andrew/projects/MongoDB_CLI/vendor/mongodb/mongodb/src/Database.php(298): MongoDB\Operation\ListCollections->execute(Object(MongoDB\Driver\Server))
#3 /Users/andrew/projects/MongoDB_CLI/mongocli.php(50): MongoDB\Database->listCollections()
#4 {main}
  thrown in /Users/andrew/projects/MongoDB_CLI/vendor/mongodb/mongodb/src/Operation/ListCollections.php on line 107
```

Я использую локально дефолтные настройки mongodb без каких либо ограничений доступа и админских ролей и не хочу их добавлять, но приложение не предусматривает такой ситуации. 

Лучше в качестве параметров mongo использовать [connection string ](https://docs.mongodb.com/manual/reference/connection-string/) и не заморачиваться. В нем можно указать все, что угодно.

**Comment by solmeer** [comment]
Постараюся чимшвидше пофіксити

**Comment by dronchik** [comment]
Ок, спасибо.
